### ISSUE TITLE
are keywords in epJSON case sensitive

### ISSUE THREAD

**Issue by santoshphilip** [pyenergyplus/eppy3000#61]
eppy3000 treats all keys (in the JSON) as case sensitive. Does E+ do the same. or does it not care ?
Run a test to check this out

**Comment by airallergy** [comment]
a quick search came up [this slides](http://web.eecs.utk.edu/~jnew1/presentations/2017_IBPSA_JSON.pdf), which states that ep input now is case sensitive.

**Comment by santoshphilip** [comment]
good find. I was at that conference. I should have known :-)
So eppy3000 works correctly right now
