### ISSUE TITLE
use of super() in classes

### ISSUE THREAD

**Issue by airallergy** [pyenergyplus/eppy3000#64]
1. for classes inherited directly from the python `object` object, `super().__init__` essentially does nothing, is there other considerations you have to have kept these lines, like for consistency?

2. in python 3, say there is a `class A(object):`, `class A:` is enough; likewise, for any `class A(xxx)`, `super().yyy` is enough instead of `super(A,self).yyy`. what is your thoughts on whether or not to keep these?

**Comment by pyenergyplus** [comment]
No reason to keep any of the old ways. They got thru out of sheer momentum
